baseurl: "/"
permalink: pretty
title: "ReputeBee::"
url: "https://reputebee.github.io"
collections_dir: collections
markdown: kramdown
highlighter: rouge

sass:
  indentWidth: 4
  style: compact
  precision: 10

google_analytics_id: false # replace with "UA-XXXX"

logo:
  logo_desktop_image: img/reputebee_logo_Right_text.svg
  logo_desktop_text: "ReputeBee:: <strong>Blog</strong>"
  logo_mobile_image: img/reputebee_logo_Right_text.svg
  logo_mobile_text: "ReputeBee:: <strong>Blog</strong>"
  logo_desktop_height: "13.2mm"
  logo_desktop_width: "56mm"
  logo_mobile_height: "13.2mm"
  logo_mobile_width: "56mm"

seo:
  meta_twitter_site: "@reputebee"
  meta_twitter_creator: "@reputebee"
  meta_og_image: "https://reputebee.github.io/img/reputebee_logo_Right_text.svg"

plugins:
  - jekyll-environment-variables
  - jekyll-postcss
  - jekyll-paginate
  - jekyll-gzip

gzip:
  extensions:
    - '.html'
    - '.css'
    - '.js'

paginate: 3
paginate_path: /blog/page:num/

collections:
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      layout: category
      permalink: /category/:basename/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - vendor
  - LICENSE.md
  - LICENSE
  - README.md
  - .vscode
  - .gitignore
  - .liquidrc
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
